---
title: "Week 2: dplyr and Census"
description: "table functions and acs data."
date: 2026-09-04
---

## What We Did

<!-- CHANGE THIS: replace with your own notes -->

First we had our questions answered. And then we had a quiz

## Key Concepts

**Census**

Decennial Census  → 10 years, 10 questions, get data from everyone
American Community Survey (ACS)  → use sample, 3% of HH surveyed, estimate for the population, now there are 1-year and 5-year estimate

**Data Reliability**

Margin of Error (MOE)  → represents the range of uncertainty of an estimate 

**Important R codes**

filter()   → pick rows

select()  → pick column

mutate()  → add a new computed column

arrange()  → change order of rows, asc or desc

group_by()  → group rows by something/variable

summarize()  → summarize data


The loop: **Edit → Save → Render → Commit → Push → wait → refresh**


## Reflection

<!-- CHANGE THIS: 3-4 sentences -->

Understanding data sources reliability is important for identifying the limitations of an analysis and knowing how to address them, so we could get a better understanding of places to make a better decision. The ACS uses sampling methods to get estimation number. Therefore, it has a margin of error (MOE), which represents the range of uncertainty of an estimate. Understanding data reliability is important. If not, we may treat data from all counties as equally certain and apply policies without considering that data from smaller counties may be less representative of actual conditions.

## Questions I Still Have

-

