{
  "hash": "0183c87c3b57e21a1c27dd612a77b699",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey (ACS) data\"\nauthor: \"RYSKA\"\ndate: 2026-09-10\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n\n**In this analysis, I look at median home value across counties in Illinois state, and ask which communities we measure most and least reliably.**\n\n---\n\n## Choosing what to measure\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"IL\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B25077_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102   5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                       variable   estimate   moe\n  <chr> <chr>                      <chr>         <dbl> <dbl>\n1 17001 Adams County, Illinois     B25077_001   155900  4554\n2 17003 Alexander County, Illinois B25077_001    58700 10578\n3 17005 Bond County, Illinois      B25077_001   133100 13683\n4 17007 Boone County, Illinois     B25077_001   198600  8350\n5 17009 Brown County, Illinois     B25077_001   142200 19435\n6 17011 Bureau County, Illinois    B25077_001   121900  3733\n```\n\n\n:::\n:::\n\n\n\n\n**There are 102 rows in the data that match the number of counties in the Illinois**\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                       estimate   moe moe_pct\n   <chr>                         <dbl> <dbl>   <dbl>\n 1 Hardin County, Illinois       91700 31269    34.1\n 2 Alexander County, Illinois    58700 10578    18.0\n 3 Jasper County, Illinois      122900 17070    13.9\n 4 Hamilton County, Illinois    108800 15103    13.9\n 5 Brown County, Illinois       142200 19435    13.7\n 6 Calhoun County, Illinois     174000 21433    12.3\n 7 Pulaski County, Illinois      81000  9539    11.8\n 8 Massac County, Illinois      118000 13228    11.2\n 9 Scott County, Illinois       101700 11145    11.0\n10 Bond County, Illinois        133100 13683    10.3\n```\n\n\n:::\n:::\n\n\n\n\n**In this data, Hardin County has the largest margin of error relative to its estimate with 34.09%**\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    49\n2 Low confidence     11\n3 Moderate           42\n```\n\n\n:::\n:::\n\n\n\n\n**There are 49 counties with high confidence in reliability (moe percentage < 5%), 42 counties with moderate confidance in reliablity (5% < moe percentage < 10%), and 11 counties with low confidence reliability (moe percentage > 10%)**\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                       myvarE myvarM  popE  popM\n  <chr> <chr>                       <dbl>  <dbl> <dbl> <dbl>\n1 17001 Adams County, Illinois     155900   4554 65166    NA\n2 17003 Alexander County, Illinois  58700  10578  5042    NA\n3 17005 Bond County, Illinois      133100  13683 16627    NA\n4 17007 Boone County, Illinois     198600   8350 53316    NA\n5 17009 Brown County, Illinois     142200  19435  6320    NA\n6 17011 Bureau County, Illinois    121900   3733 33027    NA\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 5  ~ \"High confidence\",\n    moe_pct < 15 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         49        240766.\n2 Low confidence           2          4332.\n3 Moderate                51         17381.\n```\n\n\n:::\n:::\n\n\n\n\n**Average population in high confidence counties is the largest (240,766 people) compared to the other groups. On the other hand, the low confidence counties have the smallest average population with 4,332 people. Small counties tend to have low confidence reliability, while large counties tend to have high confidence reliability**\n\n---\n\n## What this means for policy\n\n\n**Census data is commonly used by policymakers as a source to develop programs. However, not all policies are perfectly suited to every area. There are many reasons for this. From an analytical perspective, understanding data sources reliability is important for identifying the limitations of an analysis and knowing how to address them, so we could get a better understanding of places to make a better decision. The ACS uses sampling methods to get estimation number. Therefore, it has a margin of error (MOE), which represents the range of uncertainty of an estimate.** \n\n**Looking at median home value data from the ACS 5-year estimates for Illinois, the MOE percentage varies from 0.6% to 34.1%. With the largest MOE percentage (34.1%), Hardin County is the area about which we have the least certainty. There is a pattern in which low confidence reliability counties has the least average population, when high confidence reliability counties has the highest. Because the ACS uses sampling methods, smaller places yield smaller samples, which tend to result in lower reliability.**\n\n**Understanding data reliability is important. If not, we may treat data from all counties as equally certain and apply policies without considering that data from smaller counties may be less representative of actual conditions. In this case, relying solely on median home value data in Illinois without considering its reliability could lead to housing assistance program application that are not well suited to Hardin County or other lower confidence counties, and smaller communities may continue to be disadvantaged.**\n\n---\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}